### ISSUE TITLE
UserInfo Packet exception

### ISSUE THREAD

**Issue by Snooxd** [exmex/DCNC#12]
Hello, I have been trying for several days to create this server and I have 2 problems, one is the image I attached.

And another is that sometimes like that connects but when it loads the lobby is locked and I get "Unknown Packet (4000)" or something, I know the number is that but I did not leave because I did not even step Of what I attach now.

Sorry for the bad English.

Snoox

Snoox
![sin titulo](https://user-images.githubusercontent.com/30429297/28814669-e97031dc-7674-11e7-81dd-8ca5e6f27f8d.png)

**Comment by exmex** [comment]
Thanks for bringing this up to my attention. I'll look into this right now and report back.

**Comment by exmex** [comment]
Please try again with the latest master branch.

**Comment by Snooxd** [comment]
How do I test the last branch? Explain more or guide me and try everything, and I help you, I'm very interested in this.

**Comment by exmex** [comment]
Delete the folder of DCNC and redownload DCNC.
https://github.com/exmex/DCNC/archive/master.zip

Recompile, and test again.

**Comment by Snooxd** [comment]
Well, at last I was able to compile and test it (the first time I did). Anyway this is unstable, at the moment what appears to me is this of the image, I suppose that the problem is in the table "servers", appears main.servers, but although I put the one of dcmm also appears.

Sometimes it arrives until dode says "Connecting to lobby" and does not advance from there.

I do not know if I explain myself very well.

In the servers table, it will be created but I do not know which columns to put it.

Sorry for the bad English.
![sin titulo](https://user-images.githubusercontent.com/30429297/28912336-361135ae-780a-11e7-82c3-713ec736e3e4.png)

**Comment by exmex** [comment]
It's to be expected that you cannot login when a table is missing and it immediately kicks you out (The connection is killed). The SQL Structure that is in this repository is not very recent, since I didn't had time to write a proper update routine. You could try manually creating the table (If you're capable to do so.) Or you could just use this temporary SQL file. (This should also be fixed with b861f78)
[dcmm.zip](https://github.com/exmex/DCNC/files/1196795/dcmm.zip) 

Anyway, please create another issue for any other issues you have (Issues that are not related to this one!)

**Comment by Snooxd** [comment]
Good, create if you create it but I do not know what should be put in the columns so I did not do it. Tonight I try and I confirm!

**Comment by exmex** [comment]
As I've not seen any feedback in the last 14 Days, I'm gonna close this. If this is still happening, please comment and I'll re-open this issue.
